[versions]
agp = "8.13.2"
android-compileSdk = "36"
android-minSdk = "33"
android-targetSdk = "36"
androidx-activity = "1.12.4"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.6"
androidx-testExt = "1.3.0"
componentsResources = "1.10.1"
composeMultiplatform = "1.10.1"
foundation = "1.10.1"
hivemqMqttClient = "1.3.12"
junit = "4.13.2"
kotlin = "2.3.10"
ktor = "3.4.0"
logback = "1.5.29"
koin = "4.2.0-RC1"
koin-plugin = "0.3.0"
datetime = "0.7.1"
kotzilla = "2.0.4"
lifecycleProcess = "2.10.0"
datastore = "1.2.0"
androidx-material3 = "1.5.0-alpha14"
materialIconsExtended = "1.7.3"
compose = "1.10.1"
material3 = "1.9.0"

[libraries]
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-material3" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

kotzilla-sdk-compose = { group = "io.kotzilla", name = "kotzilla-sdk-compose", version.ref = "kotzilla" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-server-core = { module = "io.ktor:ktor-server-core" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging" }
ktor-server-resources = { module = "io.ktor:ktor-server-resources" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host-jvm" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-client-resources = { module = "io.ktor:ktor-client-resources" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets" }

koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-ktor = { group = "io.insert-koin", name = "koin-ktor" }
koin-logger-slf4j = { group = "io.insert-koin", name = "koin-logger-slf4j" }

koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-compose = { group = "io.insert-koin", name = "koin-compose" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }

koin-annotations = { group = "io.insert-koin", name = "koin-annotations" }

hivemq-mqtt-client = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemqMqttClient" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }

material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotzilla = { id = "io.kotzilla.kotzilla-plugin", version.ref = "kotzilla" }
koin-compiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koin-plugin" }


[bundles]
ktor-server = [
    "ktor-serialization-kotlinx-json",
    "ktor-server-core",
    "ktor-server-netty",
    "ktor-server-websockets",
    "ktor-server-content-negotiation",
    "ktor-server-call-logging",
    "ktor-server-resources",
    "ktor-server-auth"
]

ktor-client = [
    "ktor-serialization-kotlinx-json",
    "ktor-client-auth",
    "ktor-client-core",
    "ktor-client-okhttp",
    "ktor-client-logging",
    "ktor-client-content-negotiation",
    "ktor-client-resources",
    "ktor-client-websockets"
]

koin-server = [
    "koin-ktor",
    "koin-logger-slf4j"
]

koin = [
    "koin-core",
    "koin-compose",
    "koin-compose-viewmodel",
    "koin-annotations"
]
